rm tld.js
touch tld.js
{
  echo "// GENERATED BY retrieve-tld.sh"
  echo "// DO NOT EDIT THIS FILE"
  printf "\n"
  echo "export const tlds = ["
  curl -s https://www.iana.org/domains/root/db | pup '#tld-table td:nth-child(1) text{}' | sort | uniq | sed -e "s/\(.*\)/\"\1\",/" | sed 1,2d
  echo "]"
} >>tld.js
